name: Build & Push to GHCR

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image_name.outputs.value }}
    permissions:
      contents: read
      packages: write

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name as lowercase repo name
        id: image_name
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE_LOWER=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "value=$IMAGE_LOWER" >> "$GITHUB_OUTPUT"

      - name: Docker build
        run: |
          docker build -t ghcr.io/${{ steps.image_name.outputs.value }}:latest .

      - name: Docker push
        run: |
          docker push ghcr.io/${{ steps.image_name.outputs.value }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure configure container image
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config container set \
              --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
              --resource-group "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}" \
              --docker-custom-image-name ${{ needs.build.outputs.image_name }}
      
    
    
