name: Build & Deploy

on:
  workflow_dispatch:
  
jobs:
  variables: 
    runs-on: ubuntu-latest
    outputs:
      image_image: ${{ steps.image_name.outputs.value }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Get image name as lowercase repo name
        id: image_name
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE_LOWER=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "value=$IMAGE_LOWER" >> "$GITHUB_OUTPUT"
  
  build:
    runs-on: ubuntu-latest
    needs: variables
    permissions:
      contents: read
      packages: write

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build UI
        run: |
          docker build \
          --build-arg VITE_ACCESS_CODE="${{ secrets.VITE_ACCESS_CODE }}" \
          --build-arg VITE_ALLOWED_IP="${{ secrets.VITE_ALLOWED_IP }}" \
          --build-arg VITE_NANIT_EMAIL="${{ secrets.VITE_NANIT_EMAIL }}" \
          --build-arg VITE_NANIT_PASSWORD="${{ secrets.VITE_NANIT_PASSWORD }}" \
          --build-arg VITE_BABY_ID="${{ secrets.VITE_BABY_ID }}" \
          --build-arg VITE_PHONE_SUFFIX="${{ secrets.VITE_PHONE_SUFFIX }}" \
          -t ghcr.io/${{ needs.variables.outputs.image_name }}:latest .

      - name: Docker Push UI
        run: |
          docker push ghcr.io/${{ needs.variables.outputs.image_name }}:latest

          
      - name: Docker Build API
        run: |
          docker build \
          --build-arg NODE_ENV="production" \
          --build-arg PORT="3001" \
          -t ghcr.io/${{ needs.variables.outputs.image_name }}.api:latest ./api

      - name: Docker Push API
        run: |
          docker push ghcr.io/${{ needs.variables.outputs.image_name }}.api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure configure container image
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp sitecontainers create \
              --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
              --resource-group "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}" \
              --sitecontainers-spec-file sitecontainers.json
      
    
    
